### ISSUE TITLE
where proton

### ISSUE THREAD

**Issue by TechStudent10** [M-E-T-Programming/met-programming.github.io#1]
My project should be on this list too 😡

![image](https://github.com/M-E-T-Programming/M-E-T-programming.github.io/assets/76978184/36fc04f3-9a0a-4ff8-bc71-82e2acdcfa32)

**Comment by Matto58** [comment]
oh ye

**Comment by Matto58** [comment]
[done](https://github.com/M-E-T-Programming/M-E-T-programming.github.io/commit/0573d2b7cd1f1a8955b77286b1cf3705221b998d)
